export const QuizData = [
    {
    "id": 1,
    "category": "Math",
    "type": 1,
    "Q_content": "What is the square route of 256?",
    "A": "12",
    "B": "16",
    "C": "14",
    "D": "15",
    "correct_answer": "16",
    "options": [`12`,`14`,`15`,`16`],
    "points": 2,
    "quiz_id": null
    },
    {
    "id": 2,
    "category": "Science",
    "type": 1,
    "Q_content": "What is the chemical formula for water?",
    "A": "H3O",
    "B": "HO2",
    "C": "H2O2",
    "D": "H2O",
    "correct_answer": "H20",
    "options": [`H2O2`,`H30`,`HO2`, `H2O`],
    "points": 2,
    "quiz_id": null
    },
    {
    "id": 3,
    "category": "English",
    "type": 1,
    "Q_content": "Which of these is a correlative conjunction function?",
    "A": "Although",
    "B": "Since",
    "C": "Neither/nor",
    "D": "After",
    "correct_answer": "Neither-nor",
    "options": [`After`,`Neither-nor`,`Since`,`Although`],
    "points": 2,
    "quiz_id": null
    },
   

    
    // {
    // "id": 4,
    // "category": "History",
    // "type": 1,
    // "Q_content": "What was the immediate trigger for the start of WWI?",
    // "A": "Assassination of Archduke Franz Ferdinand",
    // "B": "Assassination of Adolf Hitler",
    // "C": "Assassination of Benito Mussolini",
    // "D": "Assassination of Joseph Stalin",
    // "correct_answer": "A",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 5,
    // "category": "Math",
    // "type": 1,
    // "Q_content": "Which of these is a non-real number?",
    // "A": "-2",
    // "B": "2990",
    // "C": "2i",
    // "D": "1",
    // "correct_answer": "C",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 6,
    // "category": "Science",
    // "type": 1,
    // "Q_content": "Brass gets discolored in air because of the presence of which of the following gases in air?",
    // "A": "Hydrogen Sulphide",
    // "B": "Oxygen",
    // "C": "Carbon Dioxide",
    // "D": "Nitrogen",
    // "correct_answer": "A",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 7,
    // "category": "English",
    // "type": 1,
    // "Q_content": "Define the meaning of the idiom used in this question: He passed himself off as a noble man?",
    // "A": "Was regarded as",
    // "B": "Was thought to be",
    // "C": "Pretending to be",
    // "D": "Was looked upon",
    // "correct_answer": "C",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 8,
    // "category": "History",
    // "type": 1,
    // "Q_content": "What country gained its independence from the U.S. on July 4, 1946?",
    // "A": "Guam",
    // "B": "Cuba",
    // "C": "Estonia",
    // "D": "Philippines",
    // "correct_answer": "D",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 9,
    // "category": "Math",
    // "type": 1,
    // "Q_content": "What is the value of x + x(x^x) when x = 2?",
    // "A": "18",
    // "B": "10",
    // "C": "16",
    // "D": "36",
    // "correct_answer": "B",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 10,
    // "category": "Science",
    // "type": 1,
    // "Q_content": "Which of the following is a non metal that remains liquid at room temperature?",
    // "A": "Bromine",
    // "B": "Chlorine",
    // "C": "Helium",
    // "D": "Phosphorous",
    // "correct_answer": "A",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 11,
    // "category": "English",
    // "type": 1,
    // "Q_content": "Which of the following is an adverb?",
    // "A": "Easy",
    // "B": "Very Easy",
    // "C": "Easily",
    // "D": "Easier",
    // "correct_answer": "C",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 12,
    // "category": "History",
    // "type": 1,
    // "Q_content": "When did Joseph Stalin align himself with the Allied Powers?",
    // "A": "August 23, 1939",
    // "B": "December 8, 1941",
    // "C": "June 22, 1941",
    // "D": "January 1, 1942",
    // "correct_answer": "C",
    // "points": 2,
    // "quiz_id": null
    // },
    // {
    // "id": 13,
    // "category": "Math",
    // "type": 2,
    // "Q_content": "In ∆XYZ, ∠X = 55° and ∠Y = 75°. Find ∠Z?",
    // "A": "∠Z = 50°",
    // "B": "∠Z = 150°",
    // "C": "∠Z = 25°",
    // "D": "∠Z = 75°",
    // "correct_answer": "A",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 14,
    // "category": "Science",
    // "type": 2,
    // "Q_content": "Which of the following is used in pencils?",
    // "A": "Charcoal",
    // "B": "Graphite",
    // "C": "Phosphorous",
    // "D": "Lead",
    // "correct_answer": "B",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 15,
    // "category": "English",
    // "type": 2,
    // "Q_content": "Analogies: Odometer is to mileage as compass is to?",
    // "A": "Needle",
    // "B": "Speed",
    // "C": "Direction",
    // "D": "Hiking",
    // "correct_answer": "C",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 16,
    // "category": "History",
    // "type": 2,
    // "Q_content": "In 1927, who became the first man to fly solo and non-stop across the Atlantic?",
    // "A": "Charles Lindbergh",
    // "B": "Chuck Yeager",
    // "C": "Yuri Gagarin",
    // "D": "Neil Armstrong",
    // "correct_answer": "A",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 17,
    // "category": "Math",
    // "type": 2,
    // "Q_content": " If 10^2y = 25, then 10^-y equals?",
    // "A": "1/625",
    // "B": "1/25",
    // "C": "1/5",
    // "D": "-1/5",
    // "correct_answer": "C",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 18,
    // "category": "Science",
    // "type": 2,
    // "Q_content": "Which of the following metals forms an amalgam with other metals?",
    // "A": "Mercury",
    // "B": "Zinc",
    // "C": "Lead",
    // "D": "Tin",
    // "correct_answer": "A",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 19,
    // "category": "English",
    // "type": 2,
    // "Q_content": "Analogies: BINDING : BOOK?",
    // "A": "Display : museum",
    // "B": "Artist : carpenter",
    // "C": "Nail : hammer",
    // "D": "Frame : picture",
    // "correct_answer": "D",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 20,
    // "category": "History",
    // "type": 2,
    // "Q_content": "What was the family name of the Russian rulers from the 17th century until the 1917 revolution?",
    // "A": "Godunov",
    // "B": "Romanov",
    // "C": "Vasa",
    // "D": "Rurikids",
    // "correct_answer": "B",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 21,
    // "category": "Math",
    // "type": 2,
    // "Q_content": "Solve 2x^2 - 5x + 3 = 0?",
    // "A": "x = 2, 2/3",
    // "B": "x = 3/2, 1/3",
    // "C": "x = 1/2, 3",
    // "D": "x = 1, 3/2",
    // "correct_answer": "D",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 22,
    // "category": "Science",
    // "type": 2,
    // "Q_content": "The gas usually filled in the electric bulb is",
    // "A": "Carbon dioxide",
    // "B": "Hydrogen",
    // "C": "Oxygen",
    // "D": "Nitrogen",
    // "correct_answer": "D",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 23,
    // "category": "English",
    // "type": 2,
    // "Q_content": "Which of the following is a preposition for time and place?",
    // "A": "With",
    // "B": "By",
    // "C": "At",
    // "D": "Beside",
    // "correct_answer": "C",
    // "points": null,
    // "quiz_id": null
    // },
    // {
    // "id": 24,
    // "category": "History",
    // "type": 2,
    // "Q_content": "Who was responsible for the death of Alexander Hamilton?",
    // "A": "Thomas Jefferson",
    // "B": "Aaron Burr",
    // "C": "James Callender",
    // "D": "John Adams",
    // "correct_answer": "B",
    // "points": null,
    // "quiz_id": null
    // }
]



    
